n = int(input('Digite um numero para sua tabuada: '))
print(n, 'x {}'.format(n * 1))
print(n, 'x {}'.format(n * 2))
print(n, 'x {}'.format(n * 3))
print(n, 'x {}'.format(n * 4))
print(n, 'x {}'.format(n * 5))
print(n, 'x {}'.format(n * 6))
print(n, 'x {}'.format(n * 7))
print(n, 'x {}'.format(n * 8))
print(n, 'x {}'.format(n * 9))
