print('-=' * 30)
times_do_brasileirão = ('Flamengo', 'Palmeiras', 'Botafogo', 'Athletico Paranense', 'Bahia', 'Internacional', 'Cruzeiro', 'São Paulo', 'Bragantino', 'Atletico Mineiro', 'Juventude', 'Fortaleza', 'Crisciuma', 'Curitiba', 'Vasco', 'Vitoria', 'Atletico Goianiense', 'Corinthians', 'Gremio', 'Fluminense')
print(f'Lista dos times do Brasileirão: {times_do_brasileirão}')
print('-=' * 30)
print(f'Os Cinco Primeiros São{times_do_brasileirão[0:5]}')
print('-=' * 30)
print(f'Os 4 ultimos são: {times_do_brasileirão[16:20]}')
print('-=' * 30)
print(f'Times em ordem Alfabetica{sorted(times_do_brasileirão)}')
print('-=' * 30)
print('O Vitoria esta na {times_do_brasileirão.index{Vitoria}}')